window.esdocSearchIndex = [
  [
    "@smartface/router/src/native/androidrenderer.js~androidrenderer",
    "class/src/native/AndroidRenderer.js~AndroidRenderer.html",
    "<span>AndroidRenderer</span> <span class=\"search-result-import-path\">@smartface/router/src/native/AndroidRenderer.js</span>",
    "class"
  ],
  [
    "@smartface/router/src/native/bottomtabbarrouter.js~bottomtabbarrouter",
    "class/src/native/BottomTabBarRouter.js~BottomTabBarRouter.html",
    "<span>BottomTabBarRouter</span> <span class=\"search-result-import-path\">@smartface/router/src/native/BottomTabBarRouter.js</span>",
    "class"
  ],
  [
    "@smartface/router/src/native/iosrenderer.js~iosrenderer",
    "class/src/native/IOSRenderer.js~IOSRenderer.html",
    "<span>IOSRenderer</span> <span class=\"search-result-import-path\">@smartface/router/src/native/IOSRenderer.js</span>",
    "class"
  ],
  [
    "@smartface/router/src/native/nativemodalrouter.js~nativemodalrouter",
    "class/src/native/NativeModalRouter.js~NativeModalRouter.html",
    "<span>NativeModalRouter</span> <span class=\"search-result-import-path\">@smartface/router/src/native/NativeModalRouter.js</span>",
    "class"
  ],
  [
    "@smartface/router/src/native/nativerouter.js~nativerouter",
    "class/src/native/NativeRouter.js~NativeRouter.html",
    "<span>NativeRouter</span> <span class=\"search-result-import-path\">@smartface/router/src/native/NativeRouter.js</span>",
    "class"
  ],
  [
    "@smartface/router/src/native/nativerouterbase.js~nativerouterbase",
    "class/src/native/NativeRouterBase.js~NativeRouterBase.html",
    "<span>NativeRouterBase</span> <span class=\"search-result-import-path\">@smartface/router/src/native/NativeRouterBase.js</span>",
    "class"
  ],
  [
    "@smartface/router/src/native/nativestackrouter.js~nativestackrouter",
    "class/src/native/NativeStackRouter.js~NativeStackRouter.html",
    "<span>NativeStackRouter</span> <span class=\"search-result-import-path\">@smartface/router/src/native/NativeStackRouter.js</span>",
    "class"
  ],
  [
    "@smartface/router/src/native/renderer.js~renderer",
    "class/src/native/Renderer.js~Renderer.html",
    "<span>Renderer</span> <span class=\"search-result-import-path\">@smartface/router/src/native/Renderer.js</span>",
    "class"
  ],
  [
    "@smartface/router/src/router/route.js~route",
    "class/src/router/Route.js~Route.html",
    "<span>Route</span> <span class=\"search-result-import-path\">@smartface/router/src/router/Route.js</span>",
    "class"
  ],
  [
    "@smartface/router/src/router/route.js~routepath",
    "class/src/router/Route.js~RoutePath.html",
    "<span>RoutePath</span> <span class=\"search-result-import-path\">@smartface/router/src/router/Route.js</span>",
    "class"
  ],
  [
    "@smartface/router/src/router/router.js~router",
    "class/src/router/Router.js~Router.html",
    "<span>Router</span> <span class=\"search-result-import-path\">@smartface/router/src/router/Router.js</span>",
    "class"
  ],
  [
    "@smartface/router/src/common/createhistory.js~createhistory",
    "function/index.html#static-function-createHistory",
    "<span>createHistory</span> <span class=\"search-result-import-path\">@smartface/router/src/common/createHistory.js</span>",
    "function"
  ],
  [
    "@smartface/router/src/native/bottomtabbarrouter.js~createtabbaritem",
    "function/index.html#static-function-createTabBarItem",
    "<span>createTabBarItem</span> <span class=\"search-result-import-path\">@smartface/router/src/native/BottomTabBarRouter.js</span>",
    "function"
  ],
  [
    "",
    "test-file/__test__/HistoryController.test.js.html#lineNumber6",
    "HistoryController",
    "test"
  ],
  [
    "",
    "test-file/__test__/HistoryController.test.js.html#lineNumber180",
    "HistoryController can call parent go back if node history is empty",
    "test"
  ],
  [
    "",
    "test-file/__test__/HistoryController.test.js.html#lineNumber17",
    "HistoryController can check url is valid or not",
    "test"
  ],
  [
    "",
    "test-file/__test__/HistoryController.test.js.html#lineNumber11",
    "HistoryController can create nested nodes",
    "test"
  ],
  [
    "",
    "test-file/__test__/HistoryController.test.js.html#lineNumber204",
    "HistoryController can dispose",
    "test"
  ],
  [
    "",
    "test-file/__test__/HistoryController.test.js.html#lineNumber138",
    "HistoryController can go back",
    "test"
  ],
  [
    "",
    "test-file/__test__/HistoryController.test.js.html#lineNumber158",
    "HistoryController can't go back if history is empty",
    "test"
  ],
  [
    "",
    "test-file/__test__/HistoryController.test.js.html#lineNumber46",
    "HistoryController cannot be affected when children's state is chenged",
    "test"
  ],
  [
    "",
    "test-file/__test__/HistoryController.test.js.html#lineNumber34",
    "HistoryController should be fires an event when route is changed",
    "test"
  ],
  [
    "",
    "test-file/__test__/matchRoutes.test.js.html#lineNumber4",
    "Match Routes",
    "test"
  ],
  [
    "",
    "test-file/__test__/matchRoutes.test.js.html#lineNumber5",
    "Match Routes can match with param",
    "test"
  ],
  [
    "",
    "test-file/__test__/matchRoutes.test.js.html#lineNumber41",
    "Match Routes gets routes if parameter is just numeric",
    "test"
  ],
  [
    "",
    "test-file/__test__/matchRoutes.test.js.html#lineNumber98",
    "Match Routes mathes routes if parameter is alphanumeric",
    "test"
  ],
  [
    "",
    "test-file/__test__/Route.test.js.html#lineNumber4",
    "Route",
    "test"
  ],
  [
    "",
    "test-file/__test__/Route.test.js.html#lineNumber18",
    "Route can match with valid url",
    "test"
  ],
  [
    "",
    "test-file/__test__/Route.test.js.html#lineNumber46",
    "Route can run nested build methods",
    "test"
  ],
  [
    "",
    "test-file/__test__/Route.test.js.html#lineNumber60",
    "Route can't match with invalid url",
    "test"
  ],
  [
    "",
    "test-file/__test__/Route.test.js.html#lineNumber5",
    "Route has a path",
    "test"
  ],
  [
    "",
    "test-file/__test__/Route.test.js.html#lineNumber11",
    "Route has a target",
    "test"
  ],
  [
    "",
    "test-file/__test__/Router.test.js.html#lineNumber5",
    "Router",
    "test"
  ],
  [
    "",
    "test-file/__test__/Router.test.js.html#lineNumber436",
    "Router calls back to parent if its history is empty",
    "test"
  ],
  [
    "",
    "test-file/__test__/Router.test.js.html#lineNumber544",
    "Router can be blocked",
    "test"
  ],
  [
    "",
    "test-file/__test__/Router.test.js.html#lineNumber485",
    "Router can call a relative path",
    "test"
  ],
  [
    "",
    "test-file/__test__/Router.test.js.html#lineNumber617",
    "Router can call child Routers",
    "test"
  ],
  [
    "",
    "test-file/__test__/Router.test.js.html#lineNumber585",
    "Router can redirect to specified route with route-data when route has 'to' attribute",
    "test"
  ],
  [
    "",
    "test-file/__test__/Router.test.js.html#lineNumber275",
    "Router finds target by url",
    "test"
  ],
  [
    "",
    "test-file/__test__/Router.test.js.html#lineNumber25",
    "Router fires an event when history is changed",
    "test"
  ],
  [
    "",
    "test-file/__test__/Router.test.js.html#lineNumber390",
    "Router gets history back",
    "test"
  ],
  [
    "",
    "test-file/__test__/Router.test.js.html#lineNumber9",
    "Router has routes",
    "test"
  ],
  [
    "",
    "test-file/__test__/Router.test.js.html#lineNumber332",
    "Router return only root path if any route doesn't be matched",
    "test"
  ],
  [
    "",
    "test-file/__test__/Router.test.js.html#lineNumber364",
    "Router sends data and params to specified route",
    "test"
  ],
  [
    "",
    "test-file/__test__/Router.test.js.html#lineNumber53",
    "Router should add last route to child owner router.",
    "test"
  ],
  [
    "",
    "test-file/__test__/Router.test.js.html#lineNumber171",
    "Router should add last route to root router whenever a route redirects.",
    "test"
  ],
  [
    "",
    "test-file/__test__/Router.test.js.html#lineNumber678",
    "Router should be routed from child Routers",
    "test"
  ],
  [
    "",
    "test-file/__test__/Router.test.js.html#lineNumber139",
    "Router should call route's build when history goes back",
    "test"
  ],
  [
    "__test__/historycontroller.test.js",
    "test-file/__test__/HistoryController.test.js.html",
    "__test__/HistoryController.test.js",
    "testFile"
  ],
  [
    "__test__/route.test.js",
    "test-file/__test__/Route.test.js.html",
    "__test__/Route.test.js",
    "testFile"
  ],
  [
    "__test__/router.test.js",
    "test-file/__test__/Router.test.js.html",
    "__test__/Router.test.js",
    "testFile"
  ],
  [
    "__test__/matchroutes.test.js",
    "test-file/__test__/matchRoutes.test.js.html",
    "__test__/matchRoutes.test.js",
    "testFile"
  ],
  [
    "src/.external-ecmascript.js~array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array",
    "src/.external-ecmascript.js~Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~arraybuffer",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer",
    "src/.external-ecmascript.js~ArrayBuffer",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~Boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~dataview",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView",
    "src/.external-ecmascript.js~DataView",
    "external"
  ],
  [
    "src/.external-ecmascript.js~date",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date",
    "src/.external-ecmascript.js~Date",
    "external"
  ],
  [
    "src/.external-ecmascript.js~error",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error",
    "src/.external-ecmascript.js~Error",
    "external"
  ],
  [
    "src/.external-ecmascript.js~evalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError",
    "src/.external-ecmascript.js~EvalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array",
    "src/.external-ecmascript.js~Float32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float64array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array",
    "src/.external-ecmascript.js~Float64Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~Function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generator",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator",
    "src/.external-ecmascript.js~Generator",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generatorfunction",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction",
    "src/.external-ecmascript.js~GeneratorFunction",
    "external"
  ],
  [
    "src/.external-ecmascript.js~infinity",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity",
    "src/.external-ecmascript.js~Infinity",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int16Array",
    "src/.external-ecmascript.js~Int16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array",
    "src/.external-ecmascript.js~Int32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array",
    "src/.external-ecmascript.js~Int8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~internalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/InternalError",
    "src/.external-ecmascript.js~InternalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~json",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON",
    "src/.external-ecmascript.js~JSON",
    "external"
  ],
  [
    "src/.external-ecmascript.js~map",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map",
    "src/.external-ecmascript.js~Map",
    "external"
  ],
  [
    "src/.external-ecmascript.js~nan",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN",
    "src/.external-ecmascript.js~NaN",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~Number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~Object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~promise",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise",
    "src/.external-ecmascript.js~Promise",
    "external"
  ],
  [
    "src/.external-ecmascript.js~proxy",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy",
    "src/.external-ecmascript.js~Proxy",
    "external"
  ],
  [
    "src/.external-ecmascript.js~rangeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError",
    "src/.external-ecmascript.js~RangeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~referenceerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError",
    "src/.external-ecmascript.js~ReferenceError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~reflect",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect",
    "src/.external-ecmascript.js~Reflect",
    "external"
  ],
  [
    "src/.external-ecmascript.js~regexp",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp",
    "src/.external-ecmascript.js~RegExp",
    "external"
  ],
  [
    "src/.external-ecmascript.js~set",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set",
    "src/.external-ecmascript.js~Set",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~String",
    "external"
  ],
  [
    "src/.external-ecmascript.js~symbol",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol",
    "src/.external-ecmascript.js~Symbol",
    "external"
  ],
  [
    "src/.external-ecmascript.js~syntaxerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError",
    "src/.external-ecmascript.js~SyntaxError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~typeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError",
    "src/.external-ecmascript.js~TypeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~urierror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError",
    "src/.external-ecmascript.js~URIError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint16Array",
    "src/.external-ecmascript.js~Uint16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint32Array",
    "src/.external-ecmascript.js~Uint32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array",
    "src/.external-ecmascript.js~Uint8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8clampedarray",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray",
    "src/.external-ecmascript.js~Uint8ClampedArray",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakmap",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap",
    "src/.external-ecmascript.js~WeakMap",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakset",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet",
    "src/.external-ecmascript.js~WeakSet",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~null",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null",
    "src/.external-ecmascript.js~null",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~string",
    "external"
  ],
  [
    "src/.external-ecmascript.js~undefined",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined",
    "src/.external-ecmascript.js~undefined",
    "external"
  ],
  [
    "src/common/deviceos.js",
    "file/src/common/DeviceOS.js.html",
    "src/common/DeviceOS.js",
    "file"
  ],
  [
    "src/common/historyactions.js",
    "file/src/common/HistoryActions.js.html",
    "src/common/HistoryActions.js",
    "file"
  ],
  [
    "src/common/routestore.js",
    "file/src/common/RouteStore.js.html",
    "src/common/RouteStore.js",
    "file"
  ],
  [
    "src/common/createhistory.js",
    "file/src/common/createHistory.js.html",
    "src/common/createHistory.js",
    "file"
  ],
  [
    "src/common/createtransitionmanager.js",
    "file/src/common/createTransitionManager.js.html",
    "src/common/createTransitionManager.js",
    "file"
  ],
  [
    "src/common/history.js",
    "file/src/common/history.js.html",
    "src/common/history.js",
    "file"
  ],
  [
    "src/common/index.js",
    "file/src/common/index.js.html",
    "src/common/index.js",
    "file"
  ],
  [
    "src/common/matchpath.js",
    "file/src/common/matchPath.js.html",
    "src/common/matchPath.js",
    "file"
  ],
  [
    "src/common/matchroutes.js",
    "file/src/common/matchRoutes.js.html",
    "src/common/matchRoutes.js",
    "file"
  ],
  [
    "src/common/parseurl.js",
    "file/src/common/parseUrl.js.html",
    "src/common/parseUrl.js",
    "file"
  ],
  [
    "src/common/warning.js",
    "file/src/common/warning.js.html",
    "src/common/warning.js",
    "file"
  ],
  [
    "src/native/androidrenderer.js",
    "file/src/native/AndroidRenderer.js.html",
    "src/native/AndroidRenderer.js",
    "file"
  ],
  [
    "src/native/androidrenderer.js~androidrenderer#constructor",
    "class/src/native/AndroidRenderer.js~AndroidRenderer.html#instance-constructor-constructor",
    "src/native/AndroidRenderer.js~AndroidRenderer#constructor",
    "method"
  ],
  [
    "src/native/androidrenderer.js~androidrenderer#onnavigationcontrollertransition",
    "class/src/native/AndroidRenderer.js~AndroidRenderer.html#instance-method-onNavigationControllerTransition",
    "src/native/AndroidRenderer.js~AndroidRenderer#onNavigationControllerTransition",
    "method"
  ],
  [
    "src/native/androidrenderer.js~androidrenderer#popchild",
    "class/src/native/AndroidRenderer.js~AndroidRenderer.html#instance-method-popChild",
    "src/native/AndroidRenderer.js~AndroidRenderer#popChild",
    "method"
  ],
  [
    "src/native/androidrenderer.js~androidrenderer#pushchild",
    "class/src/native/AndroidRenderer.js~AndroidRenderer.html#instance-method-pushChild",
    "src/native/AndroidRenderer.js~AndroidRenderer#pushChild",
    "method"
  ],
  [
    "src/native/androidrenderer.js~androidrenderer#setchildcontrollers",
    "class/src/native/AndroidRenderer.js~AndroidRenderer.html#instance-method-setChildControllers",
    "src/native/AndroidRenderer.js~AndroidRenderer#setChildControllers",
    "method"
  ],
  [
    "src/native/androidrenderer.js~androidrenderer#show",
    "class/src/native/AndroidRenderer.js~AndroidRenderer.html#instance-method-show",
    "src/native/AndroidRenderer.js~AndroidRenderer#show",
    "method"
  ],
  [
    "src/native/bottomtabbarrouter.js",
    "file/src/native/BottomTabBarRouter.js.html",
    "src/native/BottomTabBarRouter.js",
    "file"
  ],
  [
    "src/native/bottomtabbarrouter.js~bottomtabbaritem",
    "typedef/index.html#static-typedef-BottomTabBarItem",
    "src/native/BottomTabBarRouter.js~BottomTabBarItem",
    "typedef"
  ],
  [
    "src/native/bottomtabbarrouter.js~bottomtabbarrouter#constructor",
    "class/src/native/BottomTabBarRouter.js~BottomTabBarRouter.html#instance-constructor-constructor",
    "src/native/BottomTabBarRouter.js~BottomTabBarRouter#constructor",
    "method"
  ],
  [
    "src/native/bottomtabbarrouter.js~bottomtabbarrouter#dispose",
    "class/src/native/BottomTabBarRouter.js~BottomTabBarRouter.html#instance-method-dispose",
    "src/native/BottomTabBarRouter.js~BottomTabBarRouter#dispose",
    "method"
  ],
  [
    "src/native/bottomtabbarrouter.js~bottomtabbarrouter#isvisited",
    "class/src/native/BottomTabBarRouter.js~BottomTabBarRouter.html#instance-method-isVisited",
    "src/native/BottomTabBarRouter.js~BottomTabBarRouter#isVisited",
    "method"
  ],
  [
    "src/native/bottomtabbarrouter.js~bottomtabbarrouter#rendermatches",
    "class/src/native/BottomTabBarRouter.js~BottomTabBarRouter.html#instance-method-renderMatches",
    "src/native/BottomTabBarRouter.js~BottomTabBarRouter#renderMatches",
    "method"
  ],
  [
    "src/native/bottomtabbarrouter.js~bottomtabbarrouter#resolveindex",
    "class/src/native/BottomTabBarRouter.js~BottomTabBarRouter.html#instance-method-resolveIndex",
    "src/native/BottomTabBarRouter.js~BottomTabBarRouter#resolveIndex",
    "method"
  ],
  [
    "src/native/bottomtabbarrouter.js~bottomtabbarrouter#resolveroute",
    "class/src/native/BottomTabBarRouter.js~BottomTabBarRouter.html#instance-method-resolveRoute",
    "src/native/BottomTabBarRouter.js~BottomTabBarRouter#resolveRoute",
    "method"
  ],
  [
    "src/native/bottomtabbarrouter.js~bottomtabbarrouter#routewillenter",
    "class/src/native/BottomTabBarRouter.js~BottomTabBarRouter.html#instance-method-routeWillEnter",
    "src/native/BottomTabBarRouter.js~BottomTabBarRouter#routeWillEnter",
    "method"
  ],
  [
    "src/native/bottomtabbarrouter.js~bottomtabbarrouter#setvisited",
    "class/src/native/BottomTabBarRouter.js~BottomTabBarRouter.html#instance-method-setVisited",
    "src/native/BottomTabBarRouter.js~BottomTabBarRouter#setVisited",
    "method"
  ],
  [
    "src/native/bottomtabbarrouter.js~bottomtabbarrouter.of",
    "class/src/native/BottomTabBarRouter.js~BottomTabBarRouter.html#static-method-of",
    "src/native/BottomTabBarRouter.js~BottomTabBarRouter.of",
    "method"
  ],
  [
    "src/native/bottomtabbarrouter.js~bottomtabbarrouterparams",
    "typedef/index.html#static-typedef-BottomTabBarRouterParams",
    "src/native/BottomTabBarRouter.js~BottomTabBarRouterParams",
    "typedef"
  ],
  [
    "src/native/iosrenderer.js",
    "file/src/native/IOSRenderer.js.html",
    "src/native/IOSRenderer.js",
    "file"
  ],
  [
    "src/native/iosrenderer.js~iosrenderer#addchild",
    "class/src/native/IOSRenderer.js~IOSRenderer.html#instance-method-addChild",
    "src/native/IOSRenderer.js~IOSRenderer#addChild",
    "method"
  ],
  [
    "src/native/iosrenderer.js~iosrenderer#addpageviewcontroller",
    "class/src/native/IOSRenderer.js~IOSRenderer.html#instance-method-addPageViewController",
    "src/native/IOSRenderer.js~IOSRenderer#addPageViewController",
    "method"
  ],
  [
    "src/native/iosrenderer.js~iosrenderer#constructor",
    "class/src/native/IOSRenderer.js~IOSRenderer.html#instance-constructor-constructor",
    "src/native/IOSRenderer.js~IOSRenderer#constructor",
    "method"
  ],
  [
    "src/native/iosrenderer.js~iosrenderer#onnavigationcontrollertransition",
    "class/src/native/IOSRenderer.js~IOSRenderer.html#instance-method-onNavigationControllerTransition",
    "src/native/IOSRenderer.js~IOSRenderer#onNavigationControllerTransition",
    "method"
  ],
  [
    "src/native/iosrenderer.js~iosrenderer#popchild",
    "class/src/native/IOSRenderer.js~IOSRenderer.html#instance-method-popChild",
    "src/native/IOSRenderer.js~IOSRenderer#popChild",
    "method"
  ],
  [
    "src/native/iosrenderer.js~iosrenderer#popto",
    "class/src/native/IOSRenderer.js~IOSRenderer.html#instance-method-popTo",
    "src/native/IOSRenderer.js~IOSRenderer#popTo",
    "method"
  ],
  [
    "src/native/iosrenderer.js~iosrenderer#pushchild",
    "class/src/native/IOSRenderer.js~IOSRenderer.html#instance-method-pushChild",
    "src/native/IOSRenderer.js~IOSRenderer#pushChild",
    "method"
  ],
  [
    "src/native/iosrenderer.js~iosrenderer#removechild",
    "class/src/native/IOSRenderer.js~IOSRenderer.html#instance-method-removeChild",
    "src/native/IOSRenderer.js~IOSRenderer#removeChild",
    "method"
  ],
  [
    "src/native/iosrenderer.js~iosrenderer#setchildcontrollers",
    "class/src/native/IOSRenderer.js~IOSRenderer.html#instance-method-setChildControllers",
    "src/native/IOSRenderer.js~IOSRenderer#setChildControllers",
    "method"
  ],
  [
    "src/native/iosrenderer.js~iosrenderer#show",
    "class/src/native/IOSRenderer.js~IOSRenderer.html#instance-method-show",
    "src/native/IOSRenderer.js~IOSRenderer#show",
    "method"
  ],
  [
    "src/native/iosrenderer.js~iosrenderer#showwithtransition",
    "class/src/native/IOSRenderer.js~IOSRenderer.html#instance-method-showWithTransition",
    "src/native/IOSRenderer.js~IOSRenderer#showWithTransition",
    "method"
  ],
  [
    "src/native/iostransitions.js",
    "file/src/native/IOSTransitions.js.html",
    "src/native/IOSTransitions.js",
    "file"
  ],
  [
    "src/native/nativemodalrouter.js",
    "file/src/native/NativeModalRouter.js.html",
    "src/native/NativeModalRouter.js",
    "file"
  ],
  [
    "src/native/nativemodalrouter.js~nativemodalrouter#addchildrouter",
    "class/src/native/NativeModalRouter.js~NativeModalRouter.html#instance-method-addChildRouter",
    "src/native/NativeModalRouter.js~NativeModalRouter#addChildRouter",
    "method"
  ],
  [
    "src/native/nativemodalrouter.js~nativemodalrouter#constructor",
    "class/src/native/NativeModalRouter.js~NativeModalRouter.html#instance-constructor-constructor",
    "src/native/NativeModalRouter.js~NativeModalRouter#constructor",
    "method"
  ],
  [
    "src/native/nativemodalrouter.js~nativemodalrouter#routewillenter",
    "class/src/native/NativeModalRouter.js~NativeModalRouter.html#instance-method-routeWillEnter",
    "src/native/NativeModalRouter.js~NativeModalRouter#routeWillEnter",
    "method"
  ],
  [
    "src/native/nativemodalrouter.js~nativemodalrouter.of",
    "class/src/native/NativeModalRouter.js~NativeModalRouter.html#static-method-of",
    "src/native/NativeModalRouter.js~NativeModalRouter.of",
    "method"
  ],
  [
    "src/native/nativerouter.js",
    "file/src/native/NativeRouter.js.html",
    "src/native/NativeRouter.js",
    "file"
  ],
  [
    "src/native/nativerouter.js~nativerouter#addchildrouter",
    "class/src/native/NativeRouter.js~NativeRouter.html#instance-method-addChildRouter",
    "src/native/NativeRouter.js~NativeRouter#addChildRouter",
    "method"
  ],
  [
    "src/native/nativerouter.js~nativerouter#constructor",
    "class/src/native/NativeRouter.js~NativeRouter.html#instance-constructor-constructor",
    "src/native/NativeRouter.js~NativeRouter#constructor",
    "method"
  ],
  [
    "src/native/nativerouter.js~nativerouter#routewillenter",
    "class/src/native/NativeRouter.js~NativeRouter.html#instance-method-routeWillEnter",
    "src/native/NativeRouter.js~NativeRouter#routeWillEnter",
    "method"
  ],
  [
    "src/native/nativerouter.js~nativerouter.of",
    "class/src/native/NativeRouter.js~NativeRouter.html#static-method-of",
    "src/native/NativeRouter.js~NativeRouter.of",
    "method"
  ],
  [
    "src/native/nativerouterbase.js",
    "file/src/native/NativeRouterBase.js.html",
    "src/native/NativeRouterBase.js",
    "file"
  ],
  [
    "src/native/nativestackrouter.js",
    "file/src/native/NativeStackRouter.js.html",
    "src/native/NativeStackRouter.js",
    "file"
  ],
  [
    "src/native/nativestackrouter.js~headerbarparams",
    "typedef/index.html#static-typedef-HeaderBarParams",
    "src/native/NativeStackRouter.js~HeaderBarParams",
    "typedef"
  ],
  [
    "src/native/nativestackrouter.js~nativestackrouter#addnavigatorchangelistener",
    "class/src/native/NativeStackRouter.js~NativeStackRouter.html#instance-method-addNavigatorChangeListener",
    "src/native/NativeStackRouter.js~NativeStackRouter#addNavigatorChangeListener",
    "method"
  ],
  [
    "src/native/nativestackrouter.js~nativestackrouter#constructor",
    "class/src/native/NativeStackRouter.js~NativeStackRouter.html#instance-constructor-constructor",
    "src/native/NativeStackRouter.js~NativeStackRouter#constructor",
    "method"
  ],
  [
    "src/native/nativestackrouter.js~nativestackrouter#dispose",
    "class/src/native/NativeStackRouter.js~NativeStackRouter.html#instance-method-dispose",
    "src/native/NativeStackRouter.js~NativeStackRouter#dispose",
    "method"
  ],
  [
    "src/native/nativestackrouter.js~nativestackrouter#headerbar",
    "class/src/native/NativeStackRouter.js~NativeStackRouter.html#instance-get-headerBar",
    "src/native/NativeStackRouter.js~NativeStackRouter#headerBar",
    "member"
  ],
  [
    "src/native/nativestackrouter.js~nativestackrouter#onrouterexit",
    "class/src/native/NativeStackRouter.js~NativeStackRouter.html#instance-method-onRouterExit",
    "src/native/NativeStackRouter.js~NativeStackRouter#onRouterExit",
    "method"
  ],
  [
    "src/native/nativestackrouter.js~nativestackrouter#setheaderbarparams",
    "class/src/native/NativeStackRouter.js~NativeStackRouter.html#instance-method-setHeaderBarParams",
    "src/native/NativeStackRouter.js~NativeStackRouter#setHeaderBarParams",
    "method"
  ],
  [
    "src/native/nativestackrouter.js~nativestackrouter.of",
    "class/src/native/NativeStackRouter.js~NativeStackRouter.html#static-method-of",
    "src/native/NativeStackRouter.js~NativeStackRouter.of",
    "method"
  ],
  [
    "src/native/nativestackrouter.js~nativestackrouterparams",
    "typedef/index.html#static-typedef-NativeStackRouterParams",
    "src/native/NativeStackRouter.js~NativeStackRouterParams",
    "typedef"
  ],
  [
    "src/native/nativestackrouter.js~navigationcontrollertransformevent",
    "typedef/index.html#static-typedef-NavigationControllerTransformEvent",
    "src/native/NativeStackRouter.js~NavigationControllerTransformEvent",
    "typedef"
  ],
  [
    "src/native/renderer.js",
    "file/src/native/Renderer.js.html",
    "src/native/Renderer.js",
    "file"
  ],
  [
    "src/native/renderer.js~renderer#addchild",
    "class/src/native/Renderer.js~Renderer.html#instance-method-addChild",
    "src/native/Renderer.js~Renderer#addChild",
    "method"
  ],
  [
    "src/native/renderer.js~renderer#onnavigationcontrollertransition",
    "class/src/native/Renderer.js~Renderer.html#instance-method-onNavigationControllerTransition",
    "src/native/Renderer.js~Renderer#onNavigationControllerTransition",
    "method"
  ],
  [
    "src/native/renderer.js~renderer#popchild",
    "class/src/native/Renderer.js~Renderer.html#instance-method-popChild",
    "src/native/Renderer.js~Renderer#popChild",
    "method"
  ],
  [
    "src/native/renderer.js~renderer#pushchild",
    "class/src/native/Renderer.js~Renderer.html#instance-method-pushChild",
    "src/native/Renderer.js~Renderer#pushChild",
    "method"
  ],
  [
    "src/native/renderer.js~renderer#removechild",
    "class/src/native/Renderer.js~Renderer.html#instance-method-removeChild",
    "src/native/Renderer.js~Renderer#removeChild",
    "method"
  ],
  [
    "src/native/renderer.js~renderer#setchildcontrollers",
    "class/src/native/Renderer.js~Renderer.html#instance-method-setChildControllers",
    "src/native/Renderer.js~Renderer#setChildControllers",
    "method"
  ],
  [
    "src/native/renderer.js~renderer#setrootcontroller",
    "class/src/native/Renderer.js~Renderer.html#instance-method-setRootController",
    "src/native/Renderer.js~Renderer#setRootController",
    "method"
  ],
  [
    "src/native/renderer.js~renderer#setselectedindex",
    "class/src/native/Renderer.js~Renderer.html#instance-method-setSelectedIndex",
    "src/native/Renderer.js~Renderer#setSelectedIndex",
    "method"
  ],
  [
    "src/native/renderer.js~renderer#settabbaritems",
    "class/src/native/Renderer.js~Renderer.html#instance-method-setTabBarItems",
    "src/native/Renderer.js~Renderer#setTabBarItems",
    "method"
  ],
  [
    "src/native/renderer.js~renderer#show",
    "class/src/native/Renderer.js~Renderer.html#instance-method-show",
    "src/native/Renderer.js~Renderer#show",
    "method"
  ],
  [
    "src/native/renderer.js~renderer#showwithtransition",
    "class/src/native/Renderer.js~Renderer.html#instance-method-showWithTransition",
    "src/native/Renderer.js~Renderer#showWithTransition",
    "method"
  ],
  [
    "src/native/renderer.js~renderer.setasroot",
    "class/src/native/Renderer.js~Renderer.html#static-method-setasRoot",
    "src/native/Renderer.js~Renderer.setasRoot",
    "method"
  ],
  [
    "src/native/createrenderer.js",
    "file/src/native/createRenderer.js.html",
    "src/native/createRenderer.js",
    "file"
  ],
  [
    "src/native/iosanimator.js",
    "file/src/native/iOSAnimator.js.html",
    "src/native/iOSAnimator.js",
    "file"
  ],
  [
    "src/router/route.js",
    "file/src/router/Route.js.html",
    "src/router/Route.js",
    "file"
  ],
  [
    "src/router/route.js~route#build",
    "class/src/router/Route.js~Route.html#instance-method-build",
    "src/router/Route.js~Route#build",
    "method"
  ],
  [
    "src/router/route.js~route#constructor",
    "class/src/router/Route.js~Route.html#instance-constructor-constructor",
    "src/router/Route.js~Route#constructor",
    "method"
  ],
  [
    "src/router/route.js~route#getpath",
    "class/src/router/Route.js~Route.html#instance-method-getPath",
    "src/router/Route.js~Route#getPath",
    "method"
  ],
  [
    "src/router/route.js~route#getredirectto",
    "class/src/router/Route.js~Route.html#instance-method-getRedirectto",
    "src/router/Route.js~Route#getRedirectto",
    "method"
  ],
  [
    "src/router/route.js~route#getstate",
    "class/src/router/Route.js~Route.html#instance-method-getState",
    "src/router/Route.js~Route#getState",
    "method"
  ],
  [
    "src/router/route.js~route#geturlpath",
    "class/src/router/Route.js~Route.html#instance-method-getUrlPath",
    "src/router/Route.js~Route#getUrlPath",
    "method"
  ],
  [
    "src/router/route.js~route#haspath",
    "class/src/router/Route.js~Route.html#instance-method-hasPath",
    "src/router/Route.js~Route#hasPath",
    "method"
  ],
  [
    "src/router/route.js~route#matchpath",
    "class/src/router/Route.js~Route.html#instance-method-matchPath",
    "src/router/Route.js~Route#matchPath",
    "method"
  ],
  [
    "src/router/route.js~route#routedidenter",
    "class/src/router/Route.js~Route.html#instance-method-routeDidEnter",
    "src/router/Route.js~Route#routeDidEnter",
    "method"
  ],
  [
    "src/router/route.js~route#routedidexit",
    "class/src/router/Route.js~Route.html#instance-method-routeDidExit",
    "src/router/Route.js~Route#routeDidExit",
    "method"
  ],
  [
    "src/router/route.js~route#routepath",
    "class/src/router/Route.js~Route.html#instance-get-routePath",
    "src/router/Route.js~Route#routePath",
    "member"
  ],
  [
    "src/router/route.js~route#routeshouldmatch",
    "class/src/router/Route.js~Route.html#instance-method-routeShouldMatch",
    "src/router/Route.js~Route#routeShouldMatch",
    "method"
  ],
  [
    "src/router/route.js~route#setstate",
    "class/src/router/Route.js~Route.html#instance-method-setState",
    "src/router/Route.js~Route#setState",
    "method"
  ],
  [
    "src/router/route.js~route#toobject",
    "class/src/router/Route.js~Route.html#instance-method-toObject",
    "src/router/Route.js~Route#toObject",
    "method"
  ],
  [
    "src/router/route.js~route#tostring",
    "class/src/router/Route.js~Route.html#instance-method-toString",
    "src/router/Route.js~Route#toString",
    "method"
  ],
  [
    "src/router/route.js~route.of",
    "class/src/router/Route.js~Route.html#static-method-of",
    "src/router/Route.js~Route.of",
    "method"
  ],
  [
    "src/router/route.js~routelocation",
    "typedef/index.html#static-typedef-RouteLocation",
    "src/router/Route.js~RouteLocation",
    "typedef"
  ],
  [
    "src/router/route.js~routematch",
    "typedef/index.html#static-typedef-RouteMatch",
    "src/router/Route.js~RouteMatch",
    "typedef"
  ],
  [
    "src/router/route.js~routeparams",
    "typedef/index.html#static-typedef-RouteParams",
    "src/router/Route.js~RouteParams",
    "typedef"
  ],
  [
    "src/router/route.js~routepath#clone",
    "class/src/router/Route.js~RoutePath.html#instance-method-clone",
    "src/router/Route.js~RoutePath#clone",
    "method"
  ],
  [
    "src/router/route.js~routepath#constructor",
    "class/src/router/Route.js~RoutePath.html#instance-constructor-constructor",
    "src/router/Route.js~RoutePath#constructor",
    "method"
  ],
  [
    "src/router/route.js~routepath#getpath",
    "class/src/router/Route.js~RoutePath.html#instance-method-getPath",
    "src/router/Route.js~RoutePath#getPath",
    "method"
  ],
  [
    "src/router/route.js~routepath#haspath",
    "class/src/router/Route.js~RoutePath.html#instance-method-hasPath",
    "src/router/Route.js~RoutePath#hasPath",
    "method"
  ],
  [
    "src/router/route.js~routepath#isroot",
    "class/src/router/Route.js~RoutePath.html#instance-method-isRoot",
    "src/router/Route.js~RoutePath#isRoot",
    "method"
  ],
  [
    "src/router/route.js~routepath#toobject",
    "class/src/router/Route.js~RoutePath.html#instance-method-toObject",
    "src/router/Route.js~RoutePath#toObject",
    "method"
  ],
  [
    "src/router/route.js~routepath.of",
    "class/src/router/Route.js~RoutePath.html#static-method-of",
    "src/router/Route.js~RoutePath.of",
    "method"
  ],
  [
    "src/router/route.js~routestate",
    "typedef/index.html#static-typedef-RouteState",
    "src/router/Route.js~RouteState",
    "typedef"
  ],
  [
    "src/router/router.js",
    "file/src/router/Router.js.html",
    "src/router/Router.js",
    "file"
  ],
  [
    "src/router/router.js~router#_historycontroller",
    "class/src/router/Router.js~Router.html#instance-member-_historyController",
    "src/router/Router.js~Router#_historyController",
    "member"
  ],
  [
    "src/router/router.js~router#addrouteblocker",
    "class/src/router/Router.js~Router.html#instance-method-addRouteBlocker",
    "src/router/Router.js~Router#addRouteBlocker",
    "method"
  ],
  [
    "src/router/router.js~router#constructor",
    "class/src/router/Router.js~Router.html#instance-constructor-constructor",
    "src/router/Router.js~Router#constructor",
    "method"
  ],
  [
    "src/router/router.js~router#dispose",
    "class/src/router/Router.js~Router.html#instance-method-dispose",
    "src/router/Router.js~Router#dispose",
    "method"
  ],
  [
    "src/router/router.js~router#getcurrenturl",
    "class/src/router/Router.js~Router.html#instance-method-getCurrentUrl",
    "src/router/Router.js~Router#getCurrentUrl",
    "method"
  ],
  [
    "src/router/router.js~router#gethistoryasarray",
    "class/src/router/Router.js~Router.html#instance-method-getHistoryasArray",
    "src/router/Router.js~Router#getHistoryasArray",
    "method"
  ],
  [
    "src/router/router.js~router#getlocation",
    "class/src/router/Router.js~Router.html#instance-method-getLocation",
    "src/router/Router.js~Router#getLocation",
    "method"
  ],
  [
    "src/router/router.js~router#goback",
    "class/src/router/Router.js~Router.html#instance-method-goBack",
    "src/router/Router.js~Router#goBack",
    "method"
  ],
  [
    "src/router/router.js~router#goforward",
    "class/src/router/Router.js~Router.html#instance-method-goForward",
    "src/router/Router.js~Router#goForward",
    "method"
  ],
  [
    "src/router/router.js~router#initialize",
    "class/src/router/Router.js~Router.html#instance-method-initialize",
    "src/router/Router.js~Router#initialize",
    "method"
  ],
  [
    "src/router/router.js~router#listen",
    "class/src/router/Router.js~Router.html#instance-method-listen",
    "src/router/Router.js~Router#listen",
    "method"
  ],
  [
    "src/router/router.js~router#map",
    "class/src/router/Router.js~Router.html#instance-method-map",
    "src/router/Router.js~Router#map",
    "method"
  ],
  [
    "src/router/router.js~router#onhistorychange",
    "class/src/router/Router.js~Router.html#instance-method-onHistoryChange",
    "src/router/Router.js~Router#onHistoryChange",
    "method"
  ],
  [
    "src/router/router.js~router#push",
    "class/src/router/Router.js~Router.html#instance-method-push",
    "src/router/Router.js~Router#push",
    "method"
  ],
  [
    "src/router/router.js~router#pushroute",
    "class/src/router/Router.js~Router.html#instance-method-pushRoute",
    "src/router/Router.js~Router#pushRoute",
    "method"
  ],
  [
    "src/router/router.js~router#redirectroute",
    "class/src/router/Router.js~Router.html#instance-method-redirectRoute",
    "src/router/Router.js~Router#redirectRoute",
    "method"
  ],
  [
    "src/router/router.js~router#rendermatches",
    "class/src/router/Router.js~Router.html#instance-method-renderMatches",
    "src/router/Router.js~Router#renderMatches",
    "method"
  ],
  [
    "src/router/router.js~router#renderroute",
    "class/src/router/Router.js~Router.html#instance-method-renderRoute",
    "src/router/Router.js~Router#renderRoute",
    "method"
  ],
  [
    "src/router/router.js~router#routedidmatch",
    "class/src/router/Router.js~Router.html#instance-method-routeDidMatch",
    "src/router/Router.js~Router#routeDidMatch",
    "method"
  ],
  [
    "src/router/router.js~router#routerdidenter",
    "class/src/router/Router.js~Router.html#instance-method-routerDidEnter",
    "src/router/Router.js~Router#routerDidEnter",
    "method"
  ],
  [
    "src/router/router.js~router#routerdidexit",
    "class/src/router/Router.js~Router.html#instance-method-routerDidExit",
    "src/router/Router.js~Router#routerDidExit",
    "method"
  ],
  [
    "src/router/router.js~router#routerwillenter",
    "class/src/router/Router.js~Router.html#instance-method-routerWillEnter",
    "src/router/Router.js~Router#routerWillEnter",
    "method"
  ],
  [
    "src/router/router.js~router#setasactiverouter",
    "class/src/router/Router.js~Router.html#instance-method-setasActiveRouter",
    "src/router/Router.js~Router#setasActiveRouter",
    "method"
  ],
  [
    "src/router/router.js~router.of",
    "class/src/router/Router.js~Router.html#static-method-of",
    "src/router/Router.js~Router.of",
    "method"
  ],
  [
    "src/router/router.js~routerparams",
    "typedef/index.html#static-typedef-RouterParams",
    "src/router/Router.js~RouterParams",
    "typedef"
  ],
  [
    "src/types.js",
    "file/src/types.js.html",
    "src/types.js",
    "file"
  ],
  [
    "src/types.js~bottomtabbarcontroller",
    "http://docs.smartface.io/#!/api/UI.BottomTabBarController",
    "src/types.js~BottomTabbarController",
    "external"
  ],
  [
    "src/types.js~color",
    "http://docs.smartface.io/#!/api/UI.Color",
    "src/types.js~Color",
    "external"
  ],
  [
    "src/types.js~history",
    "typedef/index.html#static-typedef-History",
    "src/types.js~History",
    "typedef"
  ],
  [
    "src/types.js~historylistener",
    "typedef/index.html#static-typedef-HistoryListener",
    "src/types.js~HistoryListener",
    "typedef"
  ],
  [
    "src/types.js~image",
    "http://docs.smartface.io/#!/api/UI.Image",
    "src/types.js~Image",
    "external"
  ],
  [
    "src/types.js~navigationcontroller",
    "http://docs.smartface.io/#!/api/UI.NavigationController",
    "src/types.js~NavigationController",
    "external"
  ],
  [
    "src/types.js~page",
    "http://docs.smartface.io/#!/api/UI.Page",
    "src/types.js~Page",
    "external"
  ],
  [
    "src/types.js~routebuildhandler",
    "typedef/index.html#static-typedef-RouteBuildHandler",
    "src/types.js~RouteBuildHandler",
    "typedef"
  ],
  [
    "src/types.js~routeshouldmatchhandler",
    "typedef/index.html#static-typedef-RouteShouldMatchHandler",
    "src/types.js~RouteShouldMatchHandler",
    "typedef"
  ],
  [
    "src/types.js~routerblockhandler",
    "typedef/index.html#static-typedef-RouterBlockHandler",
    "src/types.js~RouterBlockHandler",
    "typedef"
  ],
  [
    "src/types.js~tabbaritem",
    "http://docs.smartface.io/#!/api/UI.TabBarItem",
    "src/types.js~TabBarItem",
    "external"
  ],
  [
    "src/utils/map.js",
    "file/src/utils/map.js.html",
    "src/utils/map.js",
    "file"
  ]
]